// Language switching functionality - inline translations (no fetch needed)
document.addEventListener('DOMContentLoaded', function() {
    // ====== ALL TRANSLATIONS INLINED ======
    var TRANSLATIONS = {
        en: {
            siteTitle: "茶井奶蓋專門店 Tea Well - Cheung Sha Wan Bubble Tea",
            siteDescription: "Tea Well in Cheung Sha Wan, Hong Kong — award-winning cheese milk foam tea, brown sugar boba, fruit tea, and more. Unlimited cheese foam refills. Visit us at 498 Un Chau Street.",
            navHome: "Home",
            navMenu: "Menu",
            navAbout: "About",
            navPromos: "Promos",
            navReviews: "Reviews",
            navContact: "Contact",
            announcementText: "\uD83E\uDD47 Signature Cheese Milk Foam — unlimited refills! \ plain tea available.",
            heroTitle: "Tea Well",
            heroSubtitle: "茶井奶蓋專門店",
            heroTagline: "Hong Kong's Finest Cheese Milk Foam Tea",
            heroText: "Handcrafted bubble teas, cheese milk foam drinks, and fresh fruit teas made daily in Cheung Sha Wan. Our signature 王牌芝士奶蓋 comes with unlimited refills.",
            heroButton: "View Full Menu",
            aboutTitle: "Our Story",
            aboutText1: "Located in the heart of Cheung Sha Wan, 茶井奶蓋專門店 Tea Well is your go-to destination for premium cheese milk foam tea. We specialize in 王牌芝士奶蓋 — our award-winning cheese milk foam that you can refill unlimited times.",
            aboutText2: "From classic pearl milk tea to refreshing fruit teas, every drink is made fresh to order with quality ingredients. Come taste the difference that made us Cheung Sha Wan's favorite bubble tea spot.",
            aboutButton: "Find Us on Map",
            aboutAddress: "📍 Shop F2, G/F, Ching Wah Court, 498 Un Chau Street, Cheung Sha Wan, Kowloon",
            aboutHours: "🕐 Daily: 12:00 - 22:00",
            aboutPhone: "📞 WhatsApp: 4674 1114",
            menuTitle: "Our Menu",
            priceRange: "Prices: \$3-\$6 | Plain tea from \$2",
            menuCategory1: "Pure Tea &amp; Cheese Milk Foam",
            menuCat1Sub: "Signature cheese milk foam — unlimited refills \uD83E\uDD47",
            item1_1: "芝士皇芒 Cheese Mango",
            item1_1Desc: "Signature mango cheese tea — our crown jewel",
            item1_2: "芝士黑烏龍 Cheese Black Oolong",
            item1_2Desc: "Rich black oolong crowned with creamy cheese foam",
            item1_3: "芝士草莓牛乳 Cheese Strawberry Milk",
            item1_3Desc: "Strawberry milk topped with velvety cheese foam",
            item1_4: "奶蓋桂花烏龍茶 Milk Foam Osmanthus Oolong",
            item1_4Desc: "Floral osmanthus oolong with light milk foam",
            item1_5: "黑烏龍 Black Oolong",
            item1_5Desc: "Pure deep-roasted black oolong tea",
            item1_6: "桂花烏龍 Osmanthus Oolong",
            item1_6Desc: "Aromatic osmanthus oolong — refreshing and fragrant",
            item1_7: "四季春 Four Seasons Spring",
            item1_7Desc: "Light and floral Four Seasons Spring oolong",
            item1_8: "蜜桃烏龍 Peach Oolong",
            item1_8Desc: "Sweet peach-infused oolong tea",
            menuCategory2: "Milk Tea",
            item2_1: "經典珍珠奶茶 Classic Pearl Milk Tea",
            item2_1Price: "",
            item2_1Desc: "The classic Hong Kong-style pearl milk tea",
            item2_2: "黑糖波霸奶茶 Brown Sugar Boba Milk Tea",
            item2_2Price: "",
            item2_2Desc: "Rich brown sugar syrup with chewy boba pearls",
            item2_3: "烘焙珍珠鮮奶茶 Roasted Pearl Fresh Milk Tea",
            item2_3Price: "",
            item2_3Desc: "Toasty roasted tea with fresh milk and pearls",
            item2_4: "黑烏龍鮮奶茶 Black Oolong Fresh Milk Tea",
            item2_4Price: "",
            item2_4Desc: "Smooth black oolong with fresh milk",
            item2_5: "仙草奶茶 Herbal Jelly Milk Tea",
            item2_5Price: "",
            item2_5Desc: "Milk tea with herbal jelly — cool and refreshing",
            menuCategory3: "Fresh Milk Series",
            item3_1: "黑糖珍珠鮮奶 Brown Sugar Pearl Fresh Milk",
            item3_1Desc: "Fresh milk with brown sugar pearls",
            item3_2: "草莓牛乳 Strawberry Milk",
            item3_2Desc: "Fresh strawberry milk drink",
            item3_3: "芋香牛奶 Taro Milk",
            item3_3Desc: "Creamy taro-flavored fresh milk",
            item3_4: "More Fresh Milk Drinks Available",
            item3_4Desc: "Ask in-store for our daily fresh milk selections",
            menuCategory4: "Refreshing Series",
            item4_1: "水果茶四季春 Fruit Tea Four Seasons Spring",
            item4_1Desc: "Fresh fruit tea with Four Seasons Spring oolong base",
            item4_2: "百香果茶 Passion Fruit Tea",
            item4_2Desc: "Tangy and refreshing passion fruit tea",
            item4_3: "檸檬茶 Lemon Tea",
            item4_3Desc: "Classic Hong Kong-style lemon tea",
            item4_4: "蘆薈蜜 Aloe Honey",
            item4_4Desc: "Refreshing aloe vera with honey",
            item4_5: "More Refreshing Drinks",
            item4_5Desc: "Ask in-store for our full selection",
            item4_6: "More Refreshing Drinks",
            item4_6Desc: "Ask in-store for our full selection",
            menuCategory5: "Special Mixes &amp; Sets",
            item5_1: "套餐A: 中杯奶蓋茶 + 牛角包窩夫",
            item5_1Desc: "Set A: Medium milk foam tea + croissant waffle",
            item5_2: "沙冰 / 冰沙 Smoothies",
            item5_2Desc: "Ask about our daily smoothie flavors",
            item5_3: "More Specials",
            item5_3Desc: "Ask in-store for seasonal specials",
            addOns: "Add-Ons",
            addOnsDesc: "Boba +\$ | Coconut Jelly +\$ | Herbal Jelly +\$",
            unlimitedRefill: "\uD83E\uDD47 王牌芝士奶蓋 — Unlimited Cheese Foam Refills",
            promosTitle: "Promotions",
            promo1Badge: "SIGNATURE",
            promo1Title: "王牌芝士奶蓋 Cheese Milk Foam",
            promo1Text: "Any cheese milk foam drink comes with unlimited cheese foam refills. Yes, unlimited!",
            promo2Badge: "DEAL",
            promo2Title: "\ Plain Tea",
            promo2Text: "Get any plain pure tea for just \. Limited time offer.",
            promo3Badge: "SET",
            promo3Title: "Set A Special",
            promo3Text: "Medium milk foam tea + croissant waffle — perfect pairing!",
            promoShop: "Order Now",
            reviewsTitle: "What Customers Say on OpenRice",
            reviewsSource: "Source: OpenRice Hong Kong",
            newsletterTitle: "Stay in the Loop",
            newsletterText: "Get exclusive offers, new drink releases, and promo alerts straight to your inbox.",
            newsletterButton: "Subscribe",
            newsletterSuccess: "Thanks for subscribing! Check your inbox for a welcome offer.",
            contactTitle: "Get in Touch",
            contactName: "Name",
            contactEmail: "Email",
            contactMessage: "Message",
            contactButton: "Send Message",
            footerQuickLinks: "Quick Links",
            footerNewsletter: "Newsletter",
            footerOrderTitle: "Order On",
            footerNewsletterText: "Get updates and exclusive offers",
            footerFollowUs: "Follow Us",
            footerCopyright: "\u00a9 2026 茶井奶蓋專門店 Tea Well. All rights reserved.",
            formSuccess: "Thank you for your message! We will get back to you soon.",
            formError: "Please fill in all fields",
            formEmailError: "Please enter a valid email address",
            footerDesc: "茶井奶蓋專門店 Tea Well — premium cheese milk foam tea in Cheung Sha Wan. Handcrafted daily with love.",
            socialFollowText: "Follow us on Instagram &amp; Facebook for daily updates!"
        },
        "zh-TW": {
            siteTitle: "茶井奶蓋專門店 Tea Well - 長沙灣芝士奶蓋茶",
            siteDescription: "茶井奶蓋專門店 Tea Well 位於香港長沙灣元州街498號青華苑地下F2舖——屢獲殊榮的芝士奶蓋茶、黑糖波霸奶茶、水果茶等。芝士奶蓋無限添加。",
            navHome: "首頁",
            navMenu: "餐單",
            navAbout: "關於我們",
            navPromos: "優惠",
            navReviews: "食評",
            navContact: "聯絡我們",
            announcementText: "\uD83E\uDD47 王牌芝士奶蓋 — 無限添加！純茶  起。",
            heroTitle: "Tea Well",
            heroSubtitle: "茶井奶蓋專門店",
            heroTagline: "香港最強芝士奶蓋茶",
            heroText: "長沙灣每日新鮮手作奶茶、芝士奶蓋飲品和水果茶。我們的王牌芝士奶蓋可以無限添加。",
            heroButton: "查看完整餐單",
            aboutTitle: "我們的故事",
            aboutText1: "位於長沙灣元州街498號，茶井奶蓋專門店 Tea Well 是你品嚐頂級芝士奶蓋茶的首選。我們主打王牌芝士奶蓋——屢獲殊榮的招牌芝士奶蓋，可以無限次添加！",
            aboutText2: "從經典珍珠奶茶到清爽水果茶，每一杯都是即叫即製，選用優質食材。來嚐嚐讓長沙灣街坊最喜愛的奶茶店的與眾不同之處。",
            aboutButton: "在地圖上找到我們",
            aboutAddress: "📍 九龍長沙灣元州街498號青華苑地下F2舖",
            aboutHours: "🕐 每日：12:00 - 22:00",
            aboutPhone: "📞 WhatsApp: 4674 1114",
            menuTitle: "我們的餐單",
            priceRange: "價格：– | 純茶  起",
            menuCategory1: "純茶及芝士奶蓋",
            menuCat1Sub: "王牌芝士奶蓋 — 無限添加 \uD83E\uDD47",
            item1_1: "芝士皇芒 Cheese Mango",
            item1_1Desc: "招牌芒果芝士茶 — 我們的皇牌之選",
            item1_2: "芝士黑烏龍 Cheese Black Oolong",
            item1_2Desc: "濃郁黑烏龍配上幼滑芝士奶蓋",
            item1_3: "芝士草莓牛乳 Cheese Strawberry Milk",
            item1_3Desc: "草莓牛奶配上絲滑芝士奶蓋",
            item1_4: "奶蓋桂花烏龍茶 Milk Foam Osmanthus Oolong",
            item1_4Desc: "花香桂花烏龍配輕盈奶蓋",
            item1_5: "黑烏龍 Black Oolong",
            item1_5Desc: "純正深焙黑烏龍茶",
            item1_6: "桂花烏龍 Osmanthus Oolong",
            item1_6Desc: "芳香桂花烏龍 — 清爽回甘",
            item1_7: "四季春 Four Seasons Spring",
            item1_7Desc: "清雅四季春烏龍",
            item1_8: "蜜桃烏龍 Peach Oolong",
            item1_8Desc: "甜蜜蜜桃烏龍茶",
            menuCategory2: "奶茶",
            item2_1: "經典珍珠奶茶 Classic Pearl Milk Tea",
            item2_1Price: "",
            item2_1Desc: "經典港式珍珠奶茶",
            item2_2: "黑糖波霸奶茶 Brown Sugar Boba Milk Tea",
            item2_2Price: "",
            item2_2Desc: "濃郁黑糖配上煙韌波霸珍珠",
            item2_3: "烘焙珍珠鮮奶茶 Roasted Pearl Fresh Milk Tea",
            item2_3Price: "",
            item2_3Desc: "烘焙茶香配鮮奶和珍珠",
            item2_4: "黑烏龍鮮奶茶 Black Oolong Fresh Milk Tea",
            item2_4Price: "",
            item2_4Desc: "順滑黑烏龍配鮮奶",
            item2_5: "仙草奶茶 Herbal Jelly Milk Tea",
            item2_5Price: "",
            item2_5Desc: "仙草配奶茶 — 清涼消暑",
            menuCategory3: "鮮奶系列",
            item3_1: "黑糖珍珠鮮奶 Brown Sugar Pearl Fresh Milk",
            item3_1Desc: "鮮奶配黑糖珍珠",
            item3_2: "草莓牛乳 Strawberry Milk",
            item3_2Desc: "新鮮草莓牛奶飲品",
            item3_3: "芋香牛奶 Taro Milk",
            item3_3Desc: "香濃芋頭鮮奶",
            item3_4: "更多鮮奶飲品",
            item3_4Desc: "到店查詢每日鮮奶精選",
            menuCategory4: "清爽系列",
            item4_1: "水果茶四季春 Fruit Tea Four Seasons Spring",
            item4_1Desc: "四季春烏龍茶底配新鮮水果",
            item4_2: "百香果茶 Passion Fruit Tea",
            item4_2Desc: "酸甜清爽百香果茶",
            item4_3: "檸檬茶 Lemon Tea",
            item4_3Desc: "經典港式檸檬茶",
            item4_4: "蘆薈蜜 Aloe Honey",
            item4_4Desc: "清爽蘆薈配蜂蜜",
            item4_5: "更多清爽飲品",
            item4_5Desc: "到店查詢完整選擇",
            item4_6: "更多清爽飲品",
            item4_6Desc: "到店查詢完整選擇",
            menuCategory5: "特別調製及套餐",
            item5_1: "套餐A: 中杯奶蓋茶 + 牛角包窩夫",
            item5_1Desc: "Set A: 中杯奶蓋茶 + 牛角包窩夫",
            item5_2: "沙冰 / 冰沙 Smoothies",
            item5_2Desc: "到店查詢每日沙冰口味",
            item5_3: "更多特飲",
            item5_3Desc: "到店查詢季節限定",
            addOns: "加料",
            addOnsDesc: "波霸 + | 椰果 + | 仙草 +",
            unlimitedRefill: "\uD83E\uDD47 王牌芝士奶蓋 — 無限添加",
            promosTitle: "優惠推廣",
            promo1Badge: "招牌",
            promo1Title: "王牌芝士奶蓋 Cheese Milk Foam",
            promo1Text: "任何芝士奶蓋飲品均可無限次添加芝士奶蓋。是的，無限添加！",
            promo2Badge: "優惠",
            promo2Title: " 純茶",
            promo2Text: "任何純茶只需 。限時優惠。",
            promo3Badge: "套餐",
            promo3Title: "套餐A優惠",
            promo3Text: "中杯奶蓋茶 + 牛角包窩夫 — 完美配搭！",
            promoShop: "立即訂購",
            reviewsTitle: "顧客在 OpenRice 上的評價",
            reviewsSource: "來源：OpenRice 香港",
            newsletterTitle: "收取最新資訊",
            newsletterText: "獲取獨家優惠、新飲品上市和推廣提示，直接送到你的郵箱。",
            newsletterButton: "訂閱",
            newsletterSuccess: "多謝訂閱！請查看郵箱收取歡迎優惠。",
            contactTitle: "聯絡我們",
            contactName: "姓名",
            contactEmail: "電郵",
            contactMessage: "訊息",
            contactButton: "發送訊息",
            footerQuickLinks: "快速連結",
            footerNewsletter: "電子報",
            footerOrderTitle: "外送平台",
            footerNewsletterText: "獲取最新資訊和獨家優惠",
            footerFollowUs: "關注我們",
            footerCopyright: "\u00a9 2026 茶井奶蓋專門店 Tea Well. 版權所有。",
            formSuccess: "感謝您的留言！我們會盡快回覆您。",
            formError: "請填寫所有欄位",
            formEmailError: "請輸入有效的電郵地址",
            footerDesc: "茶井奶蓋專門店 Tea Well — 長沙灣頂級芝士奶蓋茶。每日用心手作。",
            socialFollowText: "在 Instagram 和 Facebook 上關注我們，獲取每日最新資訊！"
        },
        "zh-CN": {
            siteTitle: "茶井奶盖专门店 Tea Well - 长沙湾芝士奶盖茶",
            siteDescription: "茶井奶盖专门店 Tea Well 位于香港长沙湾元州街498号青华苑地下F2铺——屡获殊荣的芝士奶盖茶、黑糖波霸奶茶、水果茶等。芝士奶盖无限添加。",
            navHome: "首页",
            navMenu: "菜单",
            navAbout: "关于我们",
            navPromos: "优惠",
            navReviews: "点评",
            navContact: "联系我们",
            announcementText: "\uD83E\uDD47 王牌芝士奶盖 — 无限添加！纯茶  起。",
            heroTitle: "Tea Well",
            heroSubtitle: "茶井奶盖专门店",
            heroTagline: "香港最强芝士奶盖茶",
            heroText: "长沙湾每日新鲜手作奶茶、芝士奶盖饮品和水果茶。我们的王牌芝士奶盖可以无限添加。",
            heroButton: "查看完整菜单",
            aboutTitle: "我们的故事",
            aboutText1: "位于长沙湾元州街498号，茶井奶盖专门店 Tea Well 是你品尝顶级芝士奶盖茶的首选。我们主打王牌芝士奶盖——屡获殊荣的招牌芝士奶盖，可以无限次添加！",
            aboutText2: "从经典珍珠奶茶到清爽水果茶，每一杯都是即叫即制，选用优质食材。来尝尝让长沙湾街坊最喜爱的奶茶店的与众不同之处。",
            aboutButton: "在地图上找到我们",
            aboutAddress: "📍 九龙长沙湾元州街498号青华苑地下F2铺",
            aboutHours: "🕐 每日：12:00 - 22:00",
            aboutPhone: "📞 WhatsApp: 4674 1114",
            menuTitle: "我们的菜单",
            priceRange: "价格：– | 纯茶  起",
            menuCategory1: "纯茶及芝士奶盖",
            menuCat1Sub: "王牌芝士奶盖 — 无限添加 \uD83E\uDD47",
            item1_1: "芝士皇芒 Cheese Mango",
            item1_1Desc: "招牌芒果芝士茶 — 我们的王牌之选",
            item1_2: "芝士黑乌龙 Cheese Black Oolong",
            item1_2Desc: "浓郁黑乌龙配上幼滑芝士奶盖",
            item1_3: "芝士草莓牛乳 Cheese Strawberry Milk",
            item1_3Desc: "草莓牛奶配上丝滑芝士奶盖",
            item1_4: "奶盖桂花乌龙茶 Milk Foam Osmanthus Oolong",
            item1_4Desc: "花香桂花乌龙配轻盈奶盖",
            item1_5: "黑乌龙 Black Oolong",
            item1_5Desc: "纯正深焙黑乌龙茶",
            item1_6: "桂花乌龙 Osmanthus Oolong",
            item1_6Desc: "芳香桂花乌龙 — 清爽回甘",
            item1_7: "四季春 Four Seasons Spring",
            item1_7Desc: "清雅四季春乌龙",
            item1_8: "蜜桃乌龙 Peach Oolong",
            item1_8Desc: "甜蜜蜜桃乌龙茶",
            menuCategory2: "奶茶",
            item2_1: "经典珍珠奶茶 Classic Pearl Milk Tea",
            item2_1Price: "",
            item2_1Desc: "经典港式珍珠奶茶",
            item2_2: "黑糖波霸奶茶 Brown Sugar Boba Milk Tea",
            item2_2Price: "",
            item2_2Desc: "浓郁黑糖配上烟韧波霸珍珠",
            item2_3: "烘焙珍珠鲜奶茶 Roasted Pearl Fresh Milk Tea",
            item2_3Price: "",
            item2_3Desc: "烘焙茶香配鲜奶和珍珠",
            item2_4: "黑乌龙鲜奶茶 Black Oolong Fresh Milk Tea",
            item2_4Price: "",
            item2_4Desc: "顺滑黑乌龙配鲜奶",
            item2_5: "仙草奶茶 Herbal Jelly Milk Tea",
            item2_5Price: "",
            item2_5Desc: "仙草配奶茶 — 清凉消暑",
            menuCategory3: "鲜奶系列",
            item3_1: "黑糖珍珠鲜奶 Brown Sugar Pearl Fresh Milk",
            item3_1Desc: "鲜奶配黑糖珍珠",
            item3_2: "草莓牛乳 Strawberry Milk",
            item3_2Desc: "新鲜草莓牛奶饮品",
            item3_3: "芋香牛奶 Taro Milk",
            item3_3Desc: "香浓芋头鲜奶",
            item3_4: "更多鲜奶饮品",
            item3_4Desc: "到店查询每日鲜奶精选",
            menuCategory4: "清爽系列",
            item4_1: "水果茶四季春 Fruit Tea Four Seasons Spring",
            item4_1Desc: "四季春乌龙茶底配新鲜水果",
            item4_2: "百香果茶 Passion Fruit Tea",
            item4_2Desc: "酸甜清爽百香果茶",
            item4_3: "柠檬茶 Lemon Tea",
            item4_3Desc: "经典港式柠檬茶",
            item4_4: "芦荟蜜 Aloe Honey",
            item4_4Desc: "清爽芦荟配蜂蜜",
            item4_5: "更多清爽饮品",
            item4_5Desc: "到店查询完整选择",
            item4_6: "更多清爽饮品",
            item4_6Desc: "到店查询完整选择",
            menuCategory5: "特别调制及套餐",
            item5_1: "套餐A: 中杯奶盖茶 + 牛角包窝夫",
            item5_1Desc: "Set A: 中杯奶盖茶 + 牛角包窝夫",
            item5_2: "沙冰 / 冰沙 Smoothies",
            item5_2Desc: "到店查询每日沙冰口味",
            item5_3: "更多特饮",
            item5_3Desc: "到店查询季节限定",
            addOns: "加料",
            addOnsDesc: "波霸 + | 椰果 + | 仙草 +",
            unlimitedRefill: "\uD83E\uDD47 王牌芝士奶盖 — 无限添加",
            promosTitle: "优惠推广",
            promo1Badge: "招牌",
            promo1Title: "王牌芝士奶盖 Cheese Milk Foam",
            promo1Text: "任何芝士奶盖饮品均可无限次添加芝士奶盖。是的，无限添加！",
            promo2Badge: "优惠",
            promo2Title: " 纯茶",
            promo2Text: "任何纯茶只需 。限时优惠。",
            promo3Badge: "套餐",
            promo3Title: "套餐A优惠",
            promo3Text: "中杯奶盖茶 + 牛角包窝夫 — 完美配搭！",
            promoShop: "立即订购",
            reviewsTitle: "顾客在 OpenRice 上的评价",
            reviewsSource: "来源：OpenRice 香港",
            newsletterTitle: "收取最新资讯",
            newsletterText: "获取独家优惠、新饮品上市和推广提示，直接送到你的邮箱。",
            newsletterButton: "订阅",
            newsletterSuccess: "多谢订阅！请查看邮箱收取欢迎优惠。",
            contactTitle: "联系我们",
            contactName: "姓名",
            contactEmail: "电邮",
            contactMessage: "讯息",
            contactButton: "发送讯息",
            footerQuickLinks: "快速链接",
            footerNewsletter: "电子报",
            footerOrderTitle: "外卖平台",
            footerNewsletterText: "获取最新资讯和独家优惠",
            footerFollowUs: "关注我们",
            footerCopyright: "\u00a9 2026 茶井奶盖专门店 Tea Well. 版权所有。",
            formSuccess: "感谢您的留言！我们会尽快回复您。",
            formError: "请填写所有字段",
            formEmailError: "请输入有效的电邮地址",
            footerDesc: "茶井奶盖专门店 Tea Well — 长沙湾顶级芝士奶盖茶。每日用心手作。",
            socialFollowText: "在 Instagram 和 Facebook 上关注我们，获取每日最新资讯！"
        }
    };

    // ====== LOGIC ======
    var langButtons = document.querySelectorAll('.lang-btn');
    var elementsWithKeys = document.querySelectorAll('[data-key]');
    window._translations = {};

    // Set initial language to Traditional Chinese
    applyLanguage('zh-TW');

    langButtons.forEach(function(button) {
        button.addEventListener('click', function() {
            langButtons.forEach(function(btn) { btn.classList.remove('active'); });
            this.classList.add('active');
            var langCode = this.id.replace('lang-', '');
            applyLanguage(langCode);
        });
    });

    function applyLanguage(langCode) {
        var t = TRANSLATIONS[langCode];
        if (!t) return;
        window._translations = t;

        // Update all data-key elements
        elementsWithKeys.forEach(function(element) {
            var key = element.getAttribute('data-key');
            if (t[key]) {
                if (element.classList.contains('price')) return;
                element.textContent = t[key];
            }
        });

        // Update title & meta
        var titleEl = document.getElementById('pageTitle');
        if (titleEl) titleEl.textContent = t.siteTitle;
        document.title = t.siteTitle;

        var metaDesc = document.getElementById('metaDescription');
        if (metaDesc) metaDesc.setAttribute('content', t.siteDescription);

        // OG / Twitter meta
        var ogTitle = document.querySelector('meta[property="og:title"]');
        if (ogTitle) ogTitle.setAttribute('content', t.siteTitle);
        var ogDesc = document.querySelector('meta[property="og:description"]');
        if (ogDesc) ogDesc.setAttribute('content', t.siteDescription);
        var twTitle = document.querySelector('meta[name="twitter:title"]');
        if (twTitle) twTitle.setAttribute('content', t.siteTitle);
        var twDesc = document.querySelector('meta[name="twitter:description"]');
        if (twDesc) twDesc.setAttribute('content', t.siteDescription);

        // Announcement bar
        var announce = document.querySelector('.announcement-bar span');
        if (announce && t.announcementText) announce.textContent = t.announcementText;

        // HTML lang
        if (langCode === 'en') document.documentElement.lang = 'en';
        else if (langCode === 'zh-TW') document.documentElement.lang = 'zh-TW';
        else if (langCode === 'zh-CN') document.documentElement.lang = 'zh-CN';
    }
});
