// Language switching functionality - inline translations (no fetch needed)
document.addEventListener('DOMContentLoaded', function() {
    // ====== ALL TRANSLATIONS INLINED ======
    var TRANSLATIONS = {
        en: {
            siteTitle: "?嗡?憟嗉?撠?摨?Tea Well - Cheung Sha Wan Bubble Tea",
            siteDescription: "Tea Well in Cheung Sha Wan, Hong Kong ??award-winning cheese milk foam tea, brown sugar boba, fruit tea, and more. Unlimited cheese foam refills. Visit us at 498 Un Chau Street.",
            navHome: "Home",
            navMenu: "Menu",
            navAbout: "About",
            navPromos: "Promos",
            navContact: "Contact",
            announcementText: "\uD83E\uDD47 Signature Cheese Milk Foam \u2014 unlimited refills! $1 plain tea available.",
            heroTitle: "Tea Well",
            heroSubtitle: "\u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97",
            heroTagline: "Hong Kong's Finest Cheese Milk Foam Tea",
            heroText: "Handcrafted bubble teas, cheese milk foam drinks, and fresh fruit teas made daily in Cheung Sha Wan. Our signature \u738B\u724C\u916A\u58EB\u5976\u76D6 comes with unlimited refills.",
            heroButton: "View Full Menu",
            aboutTitle: "Our Story",
            aboutText1: "Located in the heart of Cheung Sha Wan, \u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97 Tea Well is your go-to destination for premium cheese milk foam tea. We specialize in \u738B\u724C\u916A\u58EB\u5976\u76D6 \u2014 our award-winning cheese milk foam that you can refill unlimited times.",
            aboutText2: "From classic pearl milk tea to refreshing fruit teas, every drink is made fresh to order with quality ingredients. Come taste the difference that made us Cheung Sha Wan's favorite bubble tea spot.",
            aboutButton: "Find Us on Map",
            aboutAddress: "Shop F2, G/F, Ching Wah Court, 498 Un Chau Street, Cheung Sha Wan, Kowloon",
            aboutHours: "Daily: 12:00 - 22:00",
            aboutPhone: "WhatsApp: 4674 1114",
            menuTitle: "Our Menu",
            menuCategory1: "Pure Tea & Cheese Milk Foam",
            menuCat1Sub: "Signature cheese milk foam \u2014 unlimited refills \uD83E\uDD47",
            item1_1: "\u916A\u58EB\u7687\u8292 Cheese Mango",
            item1_1Desc: "Signature mango cheese tea \u2014 our crown jewel",
            item1_2: "\u916A\u58EB\u9ED1\u70CF\u9F8D Cheese Black Oolong",
            item1_2Desc: "Rich black oolong crowned with creamy cheese foam",
            item1_3: "\u916A\u58EB\u8349\u8393\u725B\u4E73 Cheese Strawberry Milk",
            item1_3Desc: "Strawberry milk topped with velvety cheese foam",
            item1_4: "\u5976\u76D6\u6842\u82B1\u70CF\u9F8D\u8336 Milk Foam Osmanthus Oolong",
            item1_4Desc: "Floral osmanthus oolong with light milk foam",
            item1_5: "\u9ED1\u70CF\u9F8D Black Oolong",
            item1_5Desc: "Pure deep-roasted black oolong tea",
            item1_6: "\u6842\u82B1\u70CF\u9F8D Osmanthus Oolong",
            item1_6Desc: "Aromatic osmanthus oolong \u2014 refreshing and fragrant",
            item1_7: "\u56DB\u5B63\u6625 Four Seasons Spring",
            item1_7Desc: "Light and floral Four Seasons Spring oolong",
            item1_8: "\u871C\u6843\u70CF\u9F8D Peach Oolong",
            item1_8Desc: "Sweet peach-infused oolong tea",
            menuCategory2: "Milk Tea",
            item2_1: "\u7D93\u5178\u73CD\u73E0\u5976\u8336 Classic Pearl Milk Tea",
            item2_1Price: "$29",
            item2_1Desc: "The classic Hong Kong-style pearl milk tea",
            item2_2: "\u9ED1\u7CD6\u6CE2\u9738\u5976\u8336 Brown Sugar Boba Milk Tea",
            item2_2Price: "$30",
            item2_2Desc: "Rich brown sugar syrup with chewy boba pearls",
            item2_3: "\u70D8\u7119\u73CD\u73E0\u9BAE\u5976\u8336 Roasted Pearl Fresh Milk Tea",
            item2_3Price: "$31",
            item2_3Desc: "Toasty roasted tea with fresh milk and pearls",
            item2_4: "\u9ED1\u70CF\u9F8D\u9BAE\u5976\u8336 Black Oolong Fresh Milk Tea",
            item2_4Price: "$26",
            item2_4Desc: "Smooth black oolong with fresh milk",
            item2_5: "\u4ED9\u8349\u5976\u8336 Herbal Jelly Milk Tea",
            item2_5Price: "$29",
            item2_5Desc: "Milk tea with herbal jelly \u2014 cool and refreshing",
            menuCategory3: "Fresh Milk Series",
            item3_1: "\u9ED1\u7CD6\u73CD\u73E0\u9BAE\u5976 Brown Sugar Pearl Fresh Milk",
            item3_1Desc: "Fresh milk with brown sugar pearls",
            item3_2: "\u8349\u8393\u725B\u4E73 Strawberry Milk",
            item3_2Desc: "Fresh strawberry milk drink",
            item3_3: "\u828B\u9999\u725B\u5976 Taro Milk",
            item3_3Desc: "Creamy taro-flavored fresh milk",
            item3_4: "More Fresh Milk Drinks Available",
            item3_4Desc: "Ask in-store for our daily fresh milk selections",
            menuCategory4: "Refreshing Series",
            item4_1: "\u6C34\u679C\u8336\u56DB\u5B63\u6625 Fruit Tea Four Seasons Spring",
            item4_1Desc: "Fresh fruit tea with Four Seasons Spring oolong base",
            item4_2: "\u767E\u9999\u679C\u8336 Passion Fruit Tea",
            item4_2Desc: "Tangy and refreshing passion fruit tea",
            item4_3: "\u6A9C\u840A\u8336 Lemon Tea",
            item4_3Desc: "Classic Hong Kong-style lemon tea",
            item4_4: "\u863E\u84C9\u871C Aloe Honey",
            item4_4Desc: "Refreshing aloe vera with honey",
            item4_5: "More Refreshing Drinks",
            item4_5Desc: "Ask in-store for our full selection",
            item4_6: "More Refreshing Drinks",
            item4_6Desc: "Ask in-store for our full selection",
            menuCategory5: "Special Mixes & Sets",
            item5_1: "\u5957\u9910A: \u4E2D\u676F\u5976\u76D6\u8336 + \u725B\u89D2\u5305\u7AA9\u592B",
            item5_1Desc: "Set A: Medium milk foam tea + croissant waffle",
            item5_2: "\u6C99\u51B0 / \u51B0\u6C99 Smoothies",
            item5_2Desc: "Ask about our daily smoothie flavors",
            item5_3: "More Specials",
            item5_3Desc: "Ask in-store for seasonal specials",
            addOns: "Add-Ons",
            addOnsDesc: "Boba +$5 | Coconut Jelly +$5 | Herbal Jelly +$5",
            priceRange: "Prices: $26\u2013$31 | Plain tea from $1",
            unlimitedRefill: "\uD83E\uDD47 \u738B\u724C\u916A\u58EB\u5976\u76D6 \u2014 Unlimited Cheese Foam Refills",
            promosTitle: "Promotions",
            promo1Badge: "SIGNATURE",
            promo1Title: "\u738B\u724C\u916A\u58EB\u5976\u76D6 Cheese Milk Foam",
            promo1Text: "Any cheese milk foam drink comes with unlimited cheese foam refills. Yes, unlimited!",
            promo2Badge: "DEAL",
            promo2Title: "$1 Plain Tea",
            promo2Text: "Get any plain pure tea for just $1. Limited time offer.",
            promo3Badge: "SET",
            promo3Title: "Set A Special",
            promo3Text: "Medium milk foam tea + croissant waffle \u2014 perfect pairing!",
            promoShop: "Order Now",
            testimonialsTitle: "What Our Customers Say",
            testimonial1: "\"The cheese milk foam is out of this world! Unlimited refills is a game changer. My go-to spot in Cheung Sha Wan.\"",
            testimonial1Author: "\u2014 @foodiehk",
            testimonial2: "\"Best brown sugar boba milk tea I've had in Kowloon. The pearls are perfectly chewy every time.\"",
            testimonial2Author: "\u2014 Michelle T.",
            testimonial3: "\"Love the fruit tea Four Seasons Spring \u2014 so refreshing on a hot day. Great service too!\"",
            testimonial3Author: "\u2014 Kevin W.",
            newsletterTitle: "Stay in the Loop",
            newsletterText: "Get exclusive offers, new drink releases, and promo alerts straight to your inbox.",
            newsletterButton: "Subscribe",
            newsletterSuccess: "Thanks for subscribing! Check your inbox for a welcome offer.",
            contactTitle: "Get in Touch",
            contactName: "Name",
            contactEmail: "Email",
            contactMessage: "Message",
            contactButton: "Send Message",
            footerQuickLinks: "Quick Links",
            footerNewsletter: "Newsletter",
            footerOrderTitle: "Order On",
            footerNewsletterText: "Get updates and exclusive offers",
            footerFollowUs: "Follow Us",
            footerCopyright: "\u00a9 2026 \u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97 Tea Well. All rights reserved.",
            formSuccess: "Thank you for your message! We will get back to you soon.",
            formError: "Please fill in all fields",
            formEmailError: "Please enter a valid email address",
            footerDesc: "\u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97 Tea Well \u2014 premium cheese milk foam tea in Cheung Sha Wan. Handcrafted daily with love.",
            socialFollowText: "Follow us on Instagram & Facebook for daily updates!"
        },
        "zh-TW": {
            siteTitle: "?嗡?憟嗉?撠?摨?Tea Well - ?瑟???犖瘞??憯怠扒?",
            siteDescription: "?嗡?憟嗉?撠?摨?Tea Well 雿?瑟????撌?498???舫?唬?F2??銝餅????ㄚ憟嗉????⊿?瘛餃?嚗??貊??扒?嗚?蝟郭?詨扒?嗚偌?蝑?瘥?圈悅?矽??,
            navHome: "擐?",
            navMenu: "擗?",
            navAbout: "???,
            navPromos: "?芣?",
            navContact: "?舐窗",
            announcementText: "?? ???ㄚ憟嗉? ???⊿?瘛餃?嚗???1?芣??脰?銝准?,
            heroTitle: "Tea Well",
            heroSubtitle: "?嗡?憟嗉?撠?摨?,
            heroTagline: "擐葛?憟賢??ㄚ憟嗉???,
            heroText: "瘥?圈悅?矽?ㄚ憟嗉??嗚??扒?嗚偌?嚗蜓????憯怠扒??溶???瑟???犖瘞???詻?,
            heroButton: "?亦?摰擗?",
            aboutTitle: "??嗡?",
            aboutText1: "雿?瑟????撌?498???舫?唬?F2???嗡?憟嗉?撠?摨?Tea Well 靽????貉?憯怠扒?撠?摨??????ㄚ憟嗉????臭誑?⊿?瘛餃?嚗?銝?舫靽擙桀鋆賬?,
            aboutText2: "敺??貊??扒?嗅皜瘞湔??塚???ㄡ???∠?芾釭憌?瘥?圈悅?矽?迭餈?閰虫??????ㄡ??",
            aboutButton: "?啣?撠",
            aboutAddress: "銋??瑟????撌?498???舫?唬?F2??,
            aboutHours: "瘥嚗?2:00 - 22:00",
            aboutPhone: "WhatsApp嚗?674 1114",
            menuTitle: "憌脣?擗?",
            menuCategory1: "朣??憯怠扒?",
            menuCat1Sub: "???ㄚ憟嗉? ???⊿?瘛餃? ??",
            item1_1: "?ㄚ??",
            item1_1Desc: "?????ㄚ????????????,
            item1_2: "?ㄚ暺?樴?,
            item1_2Desc: "瞈?暺?樴?銝匱皛?憯怠扒??,
            item1_3: "?ㄚ???像",
            item1_3Desc: "???扒??蝬踹??ㄚ憟嗉?",
            item1_4: "憟嗉?獢????,
            item1_4Desc: "皜獢????頛?憟嗉?",
            item1_5: "暺?樴?,
            item1_5Desc: "蝝迤瘛梁?暺?樴",
            item1_6: "獢??",
            item1_6Desc: "獢?? ??皜???",
            item1_7: "?迤??,
            item1_7Desc: "頛??迤?仿???,
            item1_8: "????",
            item1_8Desc: "????????,
            menuCategory2: "??憟嗉",
            item2_1: "蝬??憟嗉",
            item2_1Price: "$29",
            item2_1Desc: "蝬皜臬???憟嗉",
            item2_2: "暺?瘜ａ憟嗉",
            item2_2Price: "$30",
            item2_2Desc: "瞈?暺?????瘜ａ",
            item2_3: "????擙桀扒??,
            item2_3Price: "$31",
            item2_3Desc: "?擐除?嗅??悅憟嗥???,
            item2_4: "暺?樴悅憟嗉",
            item2_4Price: "$26",
            item2_4Desc: "??暺?樴?擙桀扒",
            item2_5: "隞?憟嗉",
            item2_5Price: "$29",
            item2_5Desc: "憟嗉???賣?隞???,
            menuCategory3: "擙桀扒蝟餃?",
            item3_1: "暺???擙桀扒",
            item3_1Desc: "擙桀扒??暺???",
            item3_2: "???像",
            item3_2Desc: "?圈悅???扒",
            item3_3: "???扒",
            item3_3Desc: "擐???扒",
            item3_4: "?游?擙桀扒?豢?",
            item3_4Desc: "?游?擙桀扒蝟餃?憌脣?隢摨閰?,
            menuCategory4: "皜蝟餃?",
            item4_1: "瘞湔??嗅?摮?",
            item4_1Desc: "?迤?亥摨??圈悅瘞湔?",
            item4_2: "?暸??",
            item4_2Desc: "?貊?皜?暸??",
            item4_3: "瑼豢狀??,
            item4_3Desc: "蝬皜臬?瑼豢狀??,
            item4_4: "????,
            item4_4Desc: "皜??????,
            item4_5: "?游?皜?豢?",
            item4_5Desc: "?游?皜憌脣?隢摨閰?,
            item4_6: "?游?皜?豢?",
            item4_6Desc: "?游?皜憌脣?隢摨閰?,
            menuCategory5: "?孵隤輯ˊ??擗?,
            item5_1: "憟?A: 銝剜憟嗉???+ ???版憭?,
            item5_1Desc: "憟?A嚗葉?臬扒? + ???版憭恬?摰??",
            item5_2: "瘝 / ?唳?",
            item5_2Desc: "瘥瘝??隢摨閰?,
            item5_3: "?游??寡憌脣?",
            item5_3Desc: "摮?????寥ㄡ隢摨閰?,
            addOns: "???賊?",
            addOnsDesc: "瘜ａ +$5 | 璊唳? +$5 | 隞? +$5",
            priceRange: "?寞嚗?26??31 | 蝝雿$1",
            unlimitedRefill: "?? ???ㄚ憟嗉? ???⊿?瘛餃?",
            promosTitle: "?芣??典誨",
            promo1Badge: "銝餅?",
            promo1Title: "???ㄚ憟嗉?",
            promo1Text: "隞颱??ㄚ憟嗉?憌脣???⊿?瘛餃??ㄚ憟嗉???嚗????荔??⊿?瘛餃?嚗?,
            promo2Badge: "?芣?",
            promo2Title: "$1蝝",
            promo2Text: "隞颱?蝝?芷?$1??????砍?舫?嚗?,
            promo3Badge: "憟?",
            promo3Title: "憟?A?芣?",
            promo3Text: "銝剜憟嗉???+ ???版憭???摰?蝯?嚗?,
            promoShop: "蝡?賢",
            testimonialsTitle: "摰Ｖ犖憟質?",
            testimonial1: "\"?ㄚ憟嗉?????頛賂??⊿?瘛餃?憟賣迤嚗瘝敹?撘ㄡ???"",
            testimonial1Author: "??@foodiehk",
            testimonial2: "\"暺?瘜ａ憟嗉靽?樴?憟賡ㄡ嚗??瘥活?賜????"",
            testimonial2Author: "??撘萇??",
            testimonial3: "\"瘞湔??嗅?摮?憟賣迤嚗?憭拚ㄡ頞?皜???憟賢末嚗"",
            testimonial3Author: "???憡?,
            newsletterTitle: "閮??啗?閮?,
            newsletterText: "?脣??典振?芣????撣??典誨?嚗?亦??典??萇拳??,
            newsletterButton: "閮",
            newsletterSuccess: "憭?閮嚗?瑼Ｘ?典??駁?脣?甇∟??芣???,
            contactTitle: "?舐窗??,
            contactName: "憪?",
            contactEmail: "?駁",
            contactMessage: "閮",
            contactButton: "?潮???,
            footerQuickLinks: "敹恍??",
            footerNewsletter: "閮鞈?",
            footerOrderTitle: "憭都撟喳",
            footerNewsletterText: "?脣??芣????閮?,
            footerFollowUs: "餈質馱??,
            footerCopyright: "穢 2026 ?嗡?憟嗉?撠?摨?Tea Well??甈???,
            formSuccess: "憭??典?閮嚗????∪翰????,
            formError: "隢‵撖急???雿?,
            formEmailError: "隢撓?交????駁?啣?",
            footerDesc: "?嗡?憟嗉?撠?摨?Tea Well ???瑟???犖瘞??憯怠扒?撠?摨?瘥?圈悅?矽??,
            socialFollowText: "?釣 Instagram ??Facebook ?脣?瘥??啗?閮?"
        },
        "zh-CN": {
            siteTitle: "?嗡?憟嗥?銝摨?Tea Well - ?踵?皝曆犖瘞?憯怠扒?",
            siteDescription: "?嗡?憟嗥?銝摨?Tea Well 雿??踵?皝曉?撌?498?琿????唬?F2?綽?銝餅????ㄚ憟嗥?????瘛餃?嚗??貊??扒?嗚?蝟郭?詨扒?嗚偌?蝑?瘥?圈?????,
            navHome: "擐△",
            navMenu: "??",
            navAbout: "?喃??賑",
            navPromos: "隡?",
            navContact: "?頂",
            announcementText: "?? ???ㄚ憟嗥? ????瘛餃?嚗滲??1隡?餈?銝准?,
            heroTitle: "Tea Well",
            heroSubtitle: "?嗡?憟嗥?銝摨?,
            heroTagline: "擐葛?憟賜??ㄚ憟嗥???,
            heroText: "瘥?圈????ㄚ憟嗥??嗚??扒?嗚偌?嚗蜓????憯怠扒???溶???踵?皝曆犖瘞???,
            heroButton: "?亦?摰??",
            aboutTitle: "?喃??嗡?",
            aboutText1: "雿??踵?皝曉?撌?498?琿????唬?F2?綽??嗡?憟嗥?銝摨?Tea Well ?臭?????憯怠扒?銝摨?隞祉????ㄚ憟嗥????臭誑??瘛餃?嚗?銝?舫?舀斢?嗚?,
            aboutText2: "隞??貊??扒?嗅皜瘞湔??塚???幼???隡捶憌?瘥?圈????洽餈霂??賑???幼??",
            aboutButton: "?啣撖潸",
            aboutAddress: "銋??踵?皝曉?撌?498?琿????唬?F2??,
            aboutHours: "瘥嚗?2:00 - 22:00",
            aboutPhone: "WhatsApp嚗?674 1114",
            menuTitle: "擖桀???",
            menuCategory1: "???憯怠扒?",
            menuCat1Sub: "???ㄚ憟嗥? ????瘛餃? ??",
            item1_1: "?ㄚ??",
            item1_1Desc: "?????ㄚ?????賑??????,
            item1_2: "?ㄚ暺?樴?,
            item1_2Desc: "瘚?暺?樴?銝匱皛?憯怠扒??,
            item1_3: "?ㄚ???像",
            item1_3Desc: "???扒??蝏萄??ㄚ憟嗥?",
            item1_4: "憟嗥?獢銋???,
            item1_4Desc: "皜獢銋???頧餌?憟嗥?",
            item1_5: "暺?樴?,
            item1_5Desc: "蝥舀迤瘛梁?暺?樴",
            item1_6: "獢銋?",
            item1_6Desc: "獢銋? ??皜???",
            item1_7: "?迤??,
            item1_7Desc: "頧餌??迤?仿???,
            item1_8: "??銋?",
            item1_8Desc: "????銋???,
            menuCategory2: "??憟嗉",
            item2_1: "蝏??憟嗉",
            item2_1Price: "$29",
            item2_1Desc: "蝏皜臬???憟嗉",
            item2_2: "暺?瘜ａ憟嗉",
            item2_2Price: "$30",
            item2_2Desc: "瘚?暺????瘜ａ",
            item2_3: "????斢扒??,
            item2_3Price: "$31",
            item2_3Desc: "?擐??嗅???憟嗥???,
            item2_4: "暺?樴?憟嗉",
            item2_4Price: "$26",
            item2_4Desc: "憿箸?暺?樴?斢扒",
            item2_5: "隞?憟嗉",
            item2_5Price: "$29",
            item2_5Desc: "憟嗉???賣?隞???,
            menuCategory3: "斢扒蝟餃?",
            item3_1: "暺???斢扒",
            item3_1Desc: "斢扒??暺???",
            item3_2: "???像",
            item3_2Desc: "?圈????扒",
            item3_3: "???扒",
            item3_3Desc: "擐??仍?扒",
            item3_4: "?游?斢扒?",
            item3_4Desc: "?游?斢扒蝟餃?擖桀?霂瑕摨霂?,
            menuCategory4: "皜蝟餃?",
            item4_1: "瘞湔??嗅?摮?",
            item4_1Desc: "?迤?亥摨??圈?瘞湔?",
            item4_2: "?暸??",
            item4_2Desc: "?貊?皜?暸??",
            item4_3: "?狀??,
            item4_3Desc: "蝏皜臬??狀??,
            item4_4: "?西???,
            item4_4Desc: "皜?西?????,
            item4_5: "?游?皜?",
            item4_5Desc: "?游?皜擖桀?霂瑕摨霂?,
            item4_6: "?游?皜?",
            item4_6Desc: "?游?皜擖桀?霂瑕摨霂?,
            menuCategory5: "?孵靚??擗?,
            item5_1: "憟?A: 銝剜憟嗥???+ ????憭?,
            item5_1Desc: "憟?A嚗葉?臬扒? + ????憭恬?摰??剝?",
            item5_2: "瘝 / ?唳?",
            item5_2Desc: "瘥瘝??霂瑕摨霂?,
            item5_3: "?游??寡擖桀?",
            item5_3Desc: "摮?????寥幼霂瑕摨霂?,
            addOns: "???★",
            addOnsDesc: "瘜ａ +$5 | 璊唳? +$5 | 隞? +$5",
            priceRange: "隞瑟嚗?26??31 | 蝥航雿$1",
            unlimitedRefill: "?? ???ㄚ憟嗥? ????瘛餃?",
            promosTitle: "隡??典嘀",
            promo1Badge: "銝餅?",
            promo1Title: "???ㄚ憟嗥?",
            promo1Text: "隞颱??ㄚ憟嗥?擖桀????瘛餃??ㄚ憟嗥????雿瓷??嚗??溶??",
            promo2Badge: "隡?",
            promo2Title: "$1蝥航",
            promo2Text: "隞颱?蝥航?芷?$1???嗡???銝??嚗?,
            promo3Badge: "憟?",
            promo3Title: "憟?A隡?",
            promo3Text: "銝剜憟嗥???+ ????憭???摰?蝏?嚗?,
            promoShop: "蝡銝?",
            testimonialsTitle: "摰Ｖ犖憟質?",
            testimonial1: "\"?ㄚ憟嗥?????嚗??溶?云璉?嚗瘝嗾敹?撘幼???"",
            testimonial1Author: "??@foodiehk",
            testimonial2: "\"暺?瘜ａ憟嗉?臭?樴?憟賢?????瘥活?賜??批撕?"",
            testimonial2Author: "??撘?隞?,
            testimonial3: "\"瘞湔??嗅?摮?敺末??憭予??蝥扳??賬??∩?敺末嚗"",
            testimonial3Author: "???憡?,
            newsletterTitle: "霈ａ???啗?霈?,
            newsletterText: "?瑕??砍振隡????撣??典嘀?嚗?亙???函??桃拳??,
            newsletterButton: "霈ａ?",
            newsletterSuccess: "?陝霈ａ?嚗窈?亦??函??菟?瑕?甈Ｚ?隡???,
            contactTitle: "?頂?賑",
            contactName: "憪?",
            contactEmail: "?菟",
            contactMessage: "??",
            contactButton: "??閮",
            footerQuickLinks: "敹恍??,
            footerNewsletter: "霈ａ?韏悖",
            footerOrderTitle: "憭?撟喳",
            footerNewsletterText: "?瑕?隡?銝?縑??,
            footerFollowUs: "?單釣?賑",
            footerCopyright: "穢 2026 ?嗡?憟嗥?銝摨?Tea Well??????,
            formSuccess: "?陝?函???嚗?隞砌?撠賢翰????,
            formError: "霂瑕‵????畾?,
            formEmailError: "霂瑁??交????菟?啣?",
            footerDesc: "?嗡?憟嗥?銝摨?Tea Well ???踵?皝曆犖瘞?憯怠扒?銝摨?瘥?圈?????,
            socialFollowText: "?單釣 Instagram ??Facebook ?瑕?瘥??啗?霈荔?"
        }
    };

    // ====== LOGIC ======
    var langButtons = document.querySelectorAll('.lang-btn');
    var elementsWithKeys = document.querySelectorAll('[data-key]');
    window._translations = {};

    // Set initial language
    applyLanguage('zh-TW');

    langButtons.forEach(function(button) {
        button.addEventListener('click', function() {
            langButtons.forEach(function(btn) { btn.classList.remove('active'); });
            this.classList.add('active');
            var langCode = this.id.replace('lang-', '');
            applyLanguage(langCode);
        });
    });

    function applyLanguage(langCode) {
        var t = TRANSLATIONS[langCode];
        if (!t) return;
        window._translations = t;

        // Update all data-key elements
        elementsWithKeys.forEach(function(element) {
            var key = element.getAttribute('data-key');
            if (t[key]) {
                if (element.classList.contains('price')) return;
                element.textContent = t[key];
            }
        });

        // Update title & meta
        var titleEl = document.getElementById('pageTitle');
        if (titleEl) titleEl.textContent = t.siteTitle;
        document.title = t.siteTitle;

        var metaDesc = document.getElementById('metaDescription');
        if (metaDesc) metaDesc.setAttribute('content', t.siteDescription);

        // OG / Twitter meta
        var ogTitle = document.querySelector('meta[property="og:title"]');
        if (ogTitle) ogTitle.setAttribute('content', t.siteTitle);
        var ogDesc = document.querySelector('meta[property="og:description"]');
        if (ogDesc) ogDesc.setAttribute('content', t.siteDescription);
        var twTitle = document.querySelector('meta[name="twitter:title"]');
        if (twTitle) twTitle.setAttribute('content', t.siteTitle);
        var twDesc = document.querySelector('meta[name="twitter:description"]');
        if (twDesc) twDesc.setAttribute('content', t.siteDescription);

        // Announcement bar
        var announce = document.querySelector('.announcement-bar span');
        if (announce && t.announcementText) announce.textContent = t.announcementText;

        // HTML lang
        if (langCode === 'en') document.documentElement.lang = 'en';
        else if (langCode === 'zh-TW') document.documentElement.lang = 'zh-TW';
        else if (langCode === 'zh-CN') document.documentElement.lang = 'zh-CN';
    }
});

