// Language switching functionality - inline translations (no fetch needed)
document.addEventListener('DOMContentLoaded', function() {
    // ====== ALL TRANSLATIONS INLINED ======
    var TRANSLATIONS = {
        en: {
            siteTitle: "茶井奶蓋專門店 Tea Well - Cheung Sha Wan Bubble Tea",
            siteDescription: "Tea Well in Cheung Sha Wan, Hong Kong — award-winning cheese milk foam tea, brown sugar boba, fruit tea, and more. Unlimited cheese foam refills. Visit us at 498 Un Chau Street.",
            navHome: "Home",
            navMenu: "Menu",
            navAbout: "About",
            navPromos: "Promos",
            navContact: "Contact",
            announcementText: "\uD83E\uDD47 Signature Cheese Milk Foam \u2014 unlimited refills! $1 plain tea available.",
            heroTitle: "Tea Well",
            heroSubtitle: "\u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97",
            heroTagline: "Hong Kong's Finest Cheese Milk Foam Tea",
            heroText: "Handcrafted bubble teas, cheese milk foam drinks, and fresh fruit teas made daily in Cheung Sha Wan. Our signature \u738B\u724C\u916A\u58EB\u5976\u76D6 comes with unlimited refills.",
            heroButton: "View Full Menu",
            aboutTitle: "Our Story",
            aboutText1: "Located in the heart of Cheung Sha Wan, \u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97 Tea Well is your go-to destination for premium cheese milk foam tea. We specialize in \u738B\u724C\u916A\u58EB\u5976\u76D6 \u2014 our award-winning cheese milk foam that you can refill unlimited times.",
            aboutText2: "From classic pearl milk tea to refreshing fruit teas, every drink is made fresh to order with quality ingredients. Come taste the difference that made us Cheung Sha Wan's favorite bubble tea spot.",
            aboutButton: "Find Us on Map",
            aboutAddress: "Shop F2, G/F, Ching Wah Court, 498 Un Chau Street, Cheung Sha Wan, Kowloon",
            aboutHours: "Daily: 12:00 - 22:00",
            aboutPhone: "WhatsApp: 4674 1114",
            menuTitle: "Our Menu",
            menuCategory1: "Pure Tea & Cheese Milk Foam",
            menuCat1Sub: "Signature cheese milk foam \u2014 unlimited refills \uD83E\uDD47",
            item1_1: "\u916A\u58EB\u7687\u8292 Cheese Mango",
            item1_1Desc: "Signature mango cheese tea \u2014 our crown jewel",
            item1_2: "\u916A\u58EB\u9ED1\u70CF\u9F8D Cheese Black Oolong",
            item1_2Desc: "Rich black oolong crowned with creamy cheese foam",
            item1_3: "\u916A\u58EB\u8349\u8393\u725B\u4E73 Cheese Strawberry Milk",
            item1_3Desc: "Strawberry milk topped with velvety cheese foam",
            item1_4: "\u5976\u76D6\u6842\u82B1\u70CF\u9F8D\u8336 Milk Foam Osmanthus Oolong",
            item1_4Desc: "Floral osmanthus oolong with light milk foam",
            item1_5: "\u9ED1\u70CF\u9F8D Black Oolong",
            item1_5Desc: "Pure deep-roasted black oolong tea",
            item1_6: "\u6842\u82B1\u70CF\u9F8D Osmanthus Oolong",
            item1_6Desc: "Aromatic osmanthus oolong \u2014 refreshing and fragrant",
            item1_7: "\u56DB\u5B63\u6625 Four Seasons Spring",
            item1_7Desc: "Light and floral Four Seasons Spring oolong",
            item1_8: "\u871C\u6843\u70CF\u9F8D Peach Oolong",
            item1_8Desc: "Sweet peach-infused oolong tea",
            menuCategory2: "Milk Tea",
            item2_1: "\u7D93\u5178\u73CD\u73E0\u5976\u8336 Classic Pearl Milk Tea",
            item2_1Price: "$29",
            item2_1Desc: "The classic Hong Kong-style pearl milk tea",
            item2_2: "\u9ED1\u7CD6\u6CE2\u9738\u5976\u8336 Brown Sugar Boba Milk Tea",
            item2_2Price: "$30",
            item2_2Desc: "Rich brown sugar syrup with chewy boba pearls",
            item2_3: "\u70D8\u7119\u73CD\u73E0\u9BAE\u5976\u8336 Roasted Pearl Fresh Milk Tea",
            item2_3Price: "$31",
            item2_3Desc: "Toasty roasted tea with fresh milk and pearls",
            item2_4: "\u9ED1\u70CF\u9F8D\u9BAE\u5976\u8336 Black Oolong Fresh Milk Tea",
            item2_4Price: "$26",
            item2_4Desc: "Smooth black oolong with fresh milk",
            item2_5: "\u4ED9\u8349\u5976\u8336 Herbal Jelly Milk Tea",
            item2_5Price: "$29",
            item2_5Desc: "Milk tea with herbal jelly \u2014 cool and refreshing",
            menuCategory3: "Fresh Milk Series",
            item3_1: "\u9ED1\u7CD6\u73CD\u73E0\u9BAE\u5976 Brown Sugar Pearl Fresh Milk",
            item3_1Desc: "Fresh milk with brown sugar pearls",
            item3_2: "\u8349\u8393\u725B\u4E73 Strawberry Milk",
            item3_2Desc: "Fresh strawberry milk drink",
            item3_3: "\u828B\u9999\u725B\u5976 Taro Milk",
            item3_3Desc: "Creamy taro-flavored fresh milk",
            item3_4: "More Fresh Milk Drinks Available",
            item3_4Desc: "Ask in-store for our daily fresh milk selections",
            menuCategory4: "Refreshing Series",
            item4_1: "\u6C34\u679C\u8336\u56DB\u5B63\u6625 Fruit Tea Four Seasons Spring",
            item4_1Desc: "Fresh fruit tea with Four Seasons Spring oolong base",
            item4_2: "\u767E\u9999\u679C\u8336 Passion Fruit Tea",
            item4_2Desc: "Tangy and refreshing passion fruit tea",
            item4_3: "\u6A9C\u840A\u8336 Lemon Tea",
            item4_3Desc: "Classic Hong Kong-style lemon tea",
            item4_4: "\u863E\u84C9\u871C Aloe Honey",
            item4_4Desc: "Refreshing aloe vera with honey",
            item4_5: "More Refreshing Drinks",
            item4_5Desc: "Ask in-store for our full selection",
            item4_6: "More Refreshing Drinks",
            item4_6Desc: "Ask in-store for our full selection",
            menuCategory5: "Special Mixes & Sets",
            item5_1: "\u5957\u9910A: \u4E2D\u676F\u5976\u76D6\u8336 + \u725B\u89D2\u5305\u7AA9\u592B",
            item5_1Desc: "Set A: Medium milk foam tea + croissant waffle",
            item5_2: "\u6C99\u51B0 / \u51B0\u6C99 Smoothies",
            item5_2Desc: "Ask about our daily smoothie flavors",
            item5_3: "More Specials",
            item5_3Desc: "Ask in-store for seasonal specials",
            addOns: "Add-Ons",
            addOnsDesc: "Boba +$5 | Coconut Jelly +$5 | Herbal Jelly +$5",
            priceRange: "Prices: $26\u2013$31 | Plain tea from $1",
            unlimitedRefill: "\uD83E\uDD47 \u738B\u724C\u916A\u58EB\u5976\u76D6 \u2014 Unlimited Cheese Foam Refills",
            promosTitle: "Promotions",
            promo1Badge: "SIGNATURE",
            promo1Title: "\u738B\u724C\u916A\u58EB\u5976\u76D6 Cheese Milk Foam",
            promo1Text: "Any cheese milk foam drink comes with unlimited cheese foam refills. Yes, unlimited!",
            promo2Badge: "DEAL",
            promo2Title: "$1 Plain Tea",
            promo2Text: "Get any plain pure tea for just $1. Limited time offer.",
            promo3Badge: "SET",
            promo3Title: "Set A Special",
            promo3Text: "Medium milk foam tea + croissant waffle \u2014 perfect pairing!",
            promoShop: "Order Now",
            testimonialsTitle: "What Our Customers Say",
            testimonial1: "\"The cheese milk foam is out of this world! Unlimited refills is a game changer. My go-to spot in Cheung Sha Wan.\"",
            testimonial1Author: "\u2014 @foodiehk",
            testimonial2: "\"Best brown sugar boba milk tea I've had in Kowloon. The pearls are perfectly chewy every time.\"",
            testimonial2Author: "\u2014 Michelle T.",
            testimonial3: "\"Love the fruit tea Four Seasons Spring \u2014 so refreshing on a hot day. Great service too!\"",
            testimonial3Author: "\u2014 Kevin W.",
            newsletterTitle: "Stay in the Loop",
            newsletterText: "Get exclusive offers, new drink releases, and promo alerts straight to your inbox.",
            newsletterButton: "Subscribe",
            newsletterSuccess: "Thanks for subscribing! Check your inbox for a welcome offer.",
            contactTitle: "Get in Touch",
            contactName: "Name",
            contactEmail: "Email",
            contactMessage: "Message",
            contactButton: "Send Message",
            footerQuickLinks: "Quick Links",
            footerNewsletter: "Newsletter",
            footerOrderTitle: "Order On",
            footerNewsletterText: "Get updates and exclusive offers",
            footerFollowUs: "Follow Us",
            footerCopyright: "\u00a9 2026 \u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97 Tea Well. All rights reserved.",
            formSuccess: "Thank you for your message! We will get back to you soon.",
            formError: "Please fill in all fields",
            formEmailError: "Please enter a valid email address",
            footerDesc: "\u8336\u4E95\u5976\u76D6\u5C08\u9580\u5E97 Tea Well \u2014 premium cheese milk foam tea in Cheung Sha Wan. Handcrafted daily with love.",
            socialFollowText: "Follow us on Instagram & Facebook for daily updates!"
        },
        "zh-TW": {
            siteTitle: "茶井奶蓋專門店 Tea Well - 長沙灣人氣芝士奶蓋茶",
            siteDescription: "茶井奶蓋專門店 Tea Well 位於長沙灣元州街498號青華閣地下F2舖，主打王牌芝士奶蓋🥇無限添加，經典珍珠奶茶、黑糖波霸奶茶、水果茶等，每日新鮮手調。",
            navHome: "首頁",
            navMenu: "餐牌",
            navAbout: "關於我們",
            navPromos: "優惠",
            navContact: "聯絡",
            announcementText: "🥇 王牌芝士奶蓋 — 無限添加！純茶$1優惠進行中。",
            heroTitle: "Tea Well",
            heroSubtitle: "茶井奶蓋專門店",
            heroTagline: "香港最好嘅芝士奶蓋茶",
            heroText: "每日新鮮手調芝士奶蓋茶、珍珠奶茶、水果茶，主打王牌芝士奶蓋🥇無限添加，長沙灣人氣之選。",
            heroButton: "查看完整餐牌",
            aboutTitle: "關於茶井",
            aboutText1: "位於長沙灣元州街498號青華閣地下F2舖，茶井奶蓋專門店 Tea Well 係你嘅首選芝士奶蓋茶專門店。我哋嘅王牌芝士奶蓋🥇可以無限添加，每一杯都係新鮮即製。",
            aboutText2: "從經典珍珠奶茶到清爽水果茶，所有飲品均採用優質食材每日新鮮手調。歡迎嚟試下我哋嘅招牌飲品！",
            aboutButton: "地圖導航",
            aboutAddress: "九龍長沙灣元州街498號青華閣地下F2舖",
            aboutHours: "每日：12:00 - 22:00",
            aboutPhone: "WhatsApp：4674 1114",
            menuTitle: "飲品餐牌",
            menuCategory1: "齋茶及芝士奶蓋茶",
            menuCat1Sub: "招牌芝士奶蓋 — 無限添加 🥇",
            item1_1: "芝士皇芒",
            item1_1Desc: "招牌芒果芝士茶 — 我哋嘅皇牌之選",
            item1_2: "芝士黑烏龍",
            item1_2Desc: "濃郁黑烏龍配上幼滑芝士奶蓋",
            item1_3: "芝士草莓牛乳",
            item1_3Desc: "草莓牛奶配上綿密芝士奶蓋",
            item1_4: "奶蓋桂花烏龍茶",
            item1_4Desc: "清新桂花烏龍配上輕盈奶蓋",
            item1_5: "黑烏龍",
            item1_5Desc: "純正深烘黑烏龍茶",
            item1_6: "桂花烏龍",
            item1_6Desc: "桂花烏龍 — 清香回甘",
            item1_7: "四季春",
            item1_7Desc: "輕盈四季春青茶",
            item1_8: "蜜桃烏龍",
            item1_8Desc: "甜蜜蜜桃烏龍茶",
            menuCategory2: "醇香奶茶",
            item2_1: "經典珍珠奶茶",
            item2_1Price: "$29",
            item2_1Desc: "經典港式珍珠奶茶",
            item2_2: "黑糖波霸奶茶",
            item2_2Price: "$30",
            item2_2Desc: "濃郁黑糖配上煙韌波霸",
            item2_3: "烘焙珍珠鮮奶茶",
            item2_3Price: "$31",
            item2_3Desc: "烘烤香氣茶底配鮮奶珍珠",
            item2_4: "黑烏龍鮮奶茶",
            item2_4Price: "$26",
            item2_4Desc: "順滑黑烏龍配鮮奶",
            item2_5: "仙草奶茶",
            item2_5Price: "$29",
            item2_5Desc: "奶茶配上爽滑仙草凍",
            menuCategory3: "鮮奶系列",
            item3_1: "黑糖珍珠鮮奶",
            item3_1Desc: "鮮奶配上黑糖珍珠",
            item3_2: "草莓牛乳",
            item3_2Desc: "新鮮草莓牛奶",
            item3_3: "芋香牛奶",
            item3_3Desc: "香濃芋頭牛奶",
            item3_4: "更多鮮奶選擇",
            item3_4Desc: "更多鮮奶系列飲品請到店查詢",
            menuCategory4: "清爽系列",
            item4_1: "水果茶四季春",
            item4_1Desc: "四季春茶底配新鮮水果",
            item4_2: "百香果茶",
            item4_2Desc: "酸甜清爽百香果茶",
            item4_3: "檸檬茶",
            item4_3Desc: "經典港式檸檬茶",
            item4_4: "蘆薈蜜",
            item4_4Desc: "清爽蘆薈配蜂蜜",
            item4_5: "更多清爽選擇",
            item4_5Desc: "更多清爽飲品請到店查詢",
            item4_6: "更多清爽選擇",
            item4_6Desc: "更多清爽飲品請到店查詢",
            menuCategory5: "特別調製及套餐",
            item5_1: "套餐A: 中杯奶蓋茶 + 牛角包窩夫",
            item5_1Desc: "套餐A：中杯奶蓋茶 + 牛角包窩夫，完美配搭",
            item5_2: "沙冰 / 冰沙",
            item5_2Desc: "每日沙冰口味請到店查詢",
            item5_3: "更多特色飲品",
            item5_3Desc: "季節限定特飲請到店查詢",
            addOns: "加料選項",
            addOnsDesc: "波霸 +$5 | 椰果 +$5 | 仙草 +$5",
            priceRange: "價格：$26–$31 | 純茶低至$1",
            unlimitedRefill: "🥇 王牌芝士奶蓋 — 無限添加",
            promosTitle: "優惠推廣",
            promo1Badge: "主打",
            promo1Title: "王牌芝士奶蓋",
            promo1Text: "任何芝士奶蓋飲品均可無限添加芝士奶蓋。係，你冇睇錯，無限添加！",
            promo2Badge: "優惠",
            promo2Title: "$1純茶",
            promo2Text: "任何純茶只需$1。限時優惠，萬勿錯過！",
            promo3Badge: "套餐",
            promo3Title: "套餐A優惠",
            promo3Text: "中杯奶蓋茶 + 牛角包窩夫 — 完美組合！",
            promoShop: "立即落單",
            testimonialsTitle: "客人好評",
            testimonial1: "\"芝士奶蓋真係冇得輸！無限添加好正！長沙灣必去嘅台式飲品店。\"",
            testimonial1Author: "— @foodiehk",
            testimonial2: "\"黑糖波霸奶茶係九龍最好飲！啲珍珠每次都煙韌彈牙。\"",
            testimonial2Author: "— 張美儀",
            testimonial3: "\"水果茶四季春好正！夏天飲超級清爽。服務都好好！\"",
            testimonial3Author: "— 李健威",
            newsletterTitle: "訂閱最新資訊",
            newsletterText: "獲取獨家優惠、新品上市和推廣通知，直接發送到您嘅郵箱。",
            newsletterButton: "訂閱",
            newsletterSuccess: "多謝訂閱！請檢查您嘅電郵獲取歡迎優惠。",
            contactTitle: "聯絡我們",
            contactName: "姓名",
            contactEmail: "電郵",
            contactMessage: "訊息",
            contactButton: "發送訊息",
            footerQuickLinks: "快速連結",
            footerNewsletter: "訂閱資訊",
            footerOrderTitle: "外賣平台",
            footerNewsletterText: "獲取優惠與新品資訊",
            footerFollowUs: "追蹤我們",
            footerCopyright: "© 2026 茶井奶蓋專門店 Tea Well。版權所有。",
            formSuccess: "多謝您嘅訊息！我哋會盡快回覆。",
            formError: "請填寫所有欄位",
            formEmailError: "請輸入有效嘅電郵地址",
            footerDesc: "茶井奶蓋專門店 Tea Well — 長沙灣人氣芝士奶蓋茶專門店，每日新鮮手調。",
            socialFollowText: "關注 Instagram 及 Facebook 獲取每日最新資訊！"
        },
        "zh-CN": {
            siteTitle: "茶井奶盖专门店 Tea Well - 长沙湾人气芝士奶盖茶",
            siteDescription: "茶井奶盖专门店 Tea Well 位于长沙湾元州街498号青华阁地下F2铺，主打王牌芝士奶盖🥇无限添加，经典珍珠奶茶、黑糖波霸奶茶、水果茶等，每日新鲜手调。",
            navHome: "首页",
            navMenu: "菜单",
            navAbout: "关于我们",
            navPromos: "优惠",
            navContact: "联系",
            announcementText: "🥇 王牌芝士奶盖 — 无限添加！纯茶$1优惠进行中。",
            heroTitle: "Tea Well",
            heroSubtitle: "茶井奶盖专门店",
            heroTagline: "香港最好的芝士奶盖茶",
            heroText: "每日新鲜手调芝士奶盖茶、珍珠奶茶、水果茶，主打王牌芝士奶盖🥇无限添加，长沙湾人气之选。",
            heroButton: "查看完整菜单",
            aboutTitle: "关于茶井",
            aboutText1: "位于长沙湾元州街498号青华阁地下F2铺，茶井奶盖专门店 Tea Well 是你的首选芝士奶盖茶专门店。我们的王牌芝士奶盖🥇可以无限添加，每一杯都是新鲜现制。",
            aboutText2: "从经典珍珠奶茶到清爽水果茶，所有饮品均采用优质食材每日新鲜手调。欢迎来试试我们的招牌饮品！",
            aboutButton: "地图导航",
            aboutAddress: "九龙长沙湾元州街498号青华阁地下F2铺",
            aboutHours: "每日：12:00 - 22:00",
            aboutPhone: "WhatsApp：4674 1114",
            menuTitle: "饮品菜单",
            menuCategory1: "斋茶及芝士奶盖茶",
            menuCat1Sub: "招牌芝士奶盖 — 无限添加 🥇",
            item1_1: "芝士皇芒",
            item1_1Desc: "招牌芒果芝士茶 — 我们的皇牌之选",
            item1_2: "芝士黑乌龙",
            item1_2Desc: "浓郁黑乌龙配上幼滑芝士奶盖",
            item1_3: "芝士草莓牛乳",
            item1_3Desc: "草莓牛奶配上绵密芝士奶盖",
            item1_4: "奶盖桂花乌龙茶",
            item1_4Desc: "清新桂花乌龙配上轻盈奶盖",
            item1_5: "黑乌龙",
            item1_5Desc: "纯正深烘黑乌龙茶",
            item1_6: "桂花乌龙",
            item1_6Desc: "桂花乌龙 — 清香回甘",
            item1_7: "四季春",
            item1_7Desc: "轻盈四季春青茶",
            item1_8: "蜜桃乌龙",
            item1_8Desc: "甜蜜蜜桃乌龙茶",
            menuCategory2: "醇香奶茶",
            item2_1: "经典珍珠奶茶",
            item2_1Price: "$29",
            item2_1Desc: "经典港式珍珠奶茶",
            item2_2: "黑糖波霸奶茶",
            item2_2Price: "$30",
            item2_2Desc: "浓郁黑糖配上烟韧波霸",
            item2_3: "烘焙珍珠鲜奶茶",
            item2_3Price: "$31",
            item2_3Desc: "烘烤香气茶底配鲜奶珍珠",
            item2_4: "黑乌龙鲜奶茶",
            item2_4Price: "$26",
            item2_4Desc: "顺滑黑乌龙配鲜奶",
            item2_5: "仙草奶茶",
            item2_5Price: "$29",
            item2_5Desc: "奶茶配上爽滑仙草冻",
            menuCategory3: "鲜奶系列",
            item3_1: "黑糖珍珠鲜奶",
            item3_1Desc: "鲜奶配上黑糖珍珠",
            item3_2: "草莓牛乳",
            item3_2Desc: "新鲜草莓牛奶",
            item3_3: "芋香牛奶",
            item3_3Desc: "香浓芋头牛奶",
            item3_4: "更多鲜奶选择",
            item3_4Desc: "更多鲜奶系列饮品请到店查询",
            menuCategory4: "清爽系列",
            item4_1: "水果茶四季春",
            item4_1Desc: "四季春茶底配新鲜水果",
            item4_2: "百香果茶",
            item4_2Desc: "酸甜清爽百香果茶",
            item4_3: "柠檬茶",
            item4_3Desc: "经典港式柠檬茶",
            item4_4: "芦荟蜜",
            item4_4Desc: "清爽芦荟配蜂蜜",
            item4_5: "更多清爽选择",
            item4_5Desc: "更多清爽饮品请到店查询",
            item4_6: "更多清爽选择",
            item4_6Desc: "更多清爽饮品请到店查询",
            menuCategory5: "特别调制及套餐",
            item5_1: "套餐A: 中杯奶盖茶 + 牛角包窝夫",
            item5_1Desc: "套餐A：中杯奶盖茶 + 牛角包窝夫，完美搭配",
            item5_2: "沙冰 / 冰沙",
            item5_2Desc: "每日沙冰口味请到店查询",
            item5_3: "更多特色饮品",
            item5_3Desc: "季节限定特饮请到店查询",
            addOns: "加料选项",
            addOnsDesc: "波霸 +$5 | 椰果 +$5 | 仙草 +$5",
            priceRange: "价格：$26–$31 | 纯茶低至$1",
            unlimitedRefill: "🥇 王牌芝士奶盖 — 无限添加",
            promosTitle: "优惠推广",
            promo1Badge: "主打",
            promo1Title: "王牌芝士奶盖",
            promo1Text: "任何芝士奶盖饮品均可无限添加芝士奶盖。是的，你没看错，无限添加！",
            promo2Badge: "优惠",
            promo2Title: "$1纯茶",
            promo2Text: "任何纯茶只需$1。限时优惠，万勿错过！",
            promo3Badge: "套餐",
            promo3Title: "套餐A优惠",
            promo3Text: "中杯奶盖茶 + 牛角包窝夫 — 完美组合！",
            promoShop: "立即下单",
            testimonialsTitle: "客人好评",
            testimonial1: "\"芝士奶盖真的无敌！无限添加太棒了！长沙湾必去的台式饮品店。\"",
            testimonial1Author: "— @foodiehk",
            testimonial2: "\"黑糖波霸奶茶是九龙最好喝的！珍珠每次都烟韧弹牙。\"",
            testimonial2Author: "— 张美仪",
            testimonial3: "\"水果茶四季春很好喝！夏天喝超级清爽。服务也很好！\"",
            testimonial3Author: "— 李健威",
            newsletterTitle: "订阅最新资讯",
            newsletterText: "获取独家优惠、新品上市和推广通知，直接发送到您的邮箱。",
            newsletterButton: "订阅",
            newsletterSuccess: "感谢订阅！请查看您的电邮获取欢迎优惠。",
            contactTitle: "联系我们",
            contactName: "姓名",
            contactEmail: "电邮",
            contactMessage: "留言",
            contactButton: "发送留言",
            footerQuickLinks: "快速链接",
            footerNewsletter: "订阅资讯",
            footerOrderTitle: "外卖平台",
            footerNewsletterText: "获取优惠与新品信息",
            footerFollowUs: "关注我们",
            footerCopyright: "© 2026 茶井奶盖专门店 Tea Well。版权所有。",
            formSuccess: "感谢您的留言！我们会尽快回复。",
            formError: "请填写所有字段",
            formEmailError: "请输入有效的电邮地址",
            footerDesc: "茶井奶盖专门店 Tea Well — 长沙湾人气芝士奶盖茶专门店，每日新鲜手调。",
            socialFollowText: "关注 Instagram 及 Facebook 获取每日最新资讯！"
        }
    };

    // ====== LOGIC ======
    var langButtons = document.querySelectorAll('.lang-btn');
    var elementsWithKeys = document.querySelectorAll('[data-key]');
    window._translations = {};

    // Set initial language
    applyLanguage('en');

    langButtons.forEach(function(button) {
        button.addEventListener('click', function() {
            langButtons.forEach(function(btn) { btn.classList.remove('active'); });
            this.classList.add('active');
            var langCode = this.id.replace('lang-', '');
            applyLanguage(langCode);
        });
    });

    function applyLanguage(langCode) {
        var t = TRANSLATIONS[langCode];
        if (!t) return;
        window._translations = t;

        // Update all data-key elements
        elementsWithKeys.forEach(function(element) {
            var key = element.getAttribute('data-key');
            if (t[key]) {
                if (element.classList.contains('price')) return;
                element.textContent = t[key];
            }
        });

        // Update title & meta
        var titleEl = document.getElementById('pageTitle');
        if (titleEl) titleEl.textContent = t.siteTitle;
        document.title = t.siteTitle;

        var metaDesc = document.getElementById('metaDescription');
        if (metaDesc) metaDesc.setAttribute('content', t.siteDescription);

        // OG / Twitter meta
        var ogTitle = document.querySelector('meta[property="og:title"]');
        if (ogTitle) ogTitle.setAttribute('content', t.siteTitle);
        var ogDesc = document.querySelector('meta[property="og:description"]');
        if (ogDesc) ogDesc.setAttribute('content', t.siteDescription);
        var twTitle = document.querySelector('meta[name="twitter:title"]');
        if (twTitle) twTitle.setAttribute('content', t.siteTitle);
        var twDesc = document.querySelector('meta[name="twitter:description"]');
        if (twDesc) twDesc.setAttribute('content', t.siteDescription);

        // Announcement bar
        var announce = document.querySelector('.announcement-bar span');
        if (announce && t.announcementText) announce.textContent = t.announcementText;

        // HTML lang
        if (langCode === 'en') document.documentElement.lang = 'en';
        else if (langCode === 'zh-TW') document.documentElement.lang = 'zh-TW';
        else if (langCode === 'zh-CN') document.documentElement.lang = 'zh-CN';
    }
});
